[tool.poetry]
name = "nenos-face-tracking-repo"
version = "0.1.0"
description = "An app to track people entering and exiting the building"
authors = ["Elena-Moraru <elena.moraru306@gmail.com>"]
readme = "README.md"
packages=[{include="src"}]

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.9.2"
pytest = "^8.3.3"
pylint = "^3.3.1"
sqlalchemy = "^2.0.36"
pymysql = "^1.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
