apiVersion: v1
kind: Service
metadata:
  name: face-tracking-web
  labels:
    app: face-tracking-web
spec:
  selector:
    app: face-tracking-web
  ports:
    - protocol: TCP
      port: 8050       # Port exposed by the Service
      targetPort: 8050 # Port on the container
  type: ClusterIP # Use LoadBalancer or NodePort for external access