apiVersion: v1
kind: Service
metadata:
  name: {{ include "face-tracking.fullname" . }}-web
  labels:
    app: {{ include "face-tracking.fullname" . }}-web
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: {{ .Values.service.web.port }}
  selector:
    app: {{ include "face-tracking.fullname" . }}-web
